/* Built-in recipe library.
   Macros are per serving, estimated from USDA values for the listed ingredients.
   Ingredient rows: [quantity, unit, name, store section, optional note]. Quantities are for the whole recipe. */
window.CL = window.CL || {};

CL.SECTIONS = ["Produce","Meat & seafood","Dairy & eggs","Bakery","Canned & jars","Grains & pasta","Frozen","Pantry"];

CL.RECIPES = [
/* ---------------- Breakfast ---------------- */
{ id:"b-pb-oats", name:"Peanut butter banana overnight oats", meal:"breakfast", minutes:5, servings:1,
  kcal:410, protein:20, carbs:53, fat:15, fiber:7, diet:"vegetarian", allergens:["dairy","peanut"], tags:["make-ahead","no-cook"],
  ingredients:[[0.5,"cup","rolled oats","Grains & pasta"],[0.5,"cup","milk (2% or any)","Dairy & eggs"],[0.33,"cup","plain nonfat Greek yogurt","Dairy & eggs"],[1,"tbsp","peanut butter","Pantry"],[0.5,"","banana","Produce"],[1,"tsp","chia seeds","Pantry"]],
  steps:["Stir the oats, milk, yogurt, chia seeds and peanut butter together in a jar.","Slice the banana on top.","Cover and refrigerate overnight. Eat cold, or microwave for 1 minute."],
  tip:"Make 3–4 jars at once. They keep 4 days in the fridge." },

{ id:"b-egg-scramble", name:"Spinach and feta egg scramble on toast", meal:"breakfast", minutes:10, servings:1,
  kcal:265, protein:19, carbs:17, fat:13, fiber:3, diet:"vegetarian", allergens:["egg","dairy","gluten"], tags:[],
  ingredients:[[2,"","eggs","Dairy & eggs"],[1,"cup","baby spinach","Produce"],[0.25,"","bell pepper","Produce","diced"],[1,"tbsp","crumbled feta","Dairy & eggs"],[1,"slice","whole wheat bread","Bakery"],[1,"spray","cooking spray","Pantry"]],
  steps:["Heat a nonstick pan over medium with cooking spray.","Cook the pepper for 2 minutes, then add the spinach until it wilts.","Pour in the beaten eggs and stir gently until just set.","Sprinkle with feta and serve on toast."],
  tip:"Pull the eggs off the heat while they still look a little wet. They finish cooking on the plate." },

{ id:"b-yogurt-bowl", name:"Greek yogurt berry crunch bowl", meal:"breakfast", minutes:3, servings:1,
  kcal:345, protein:27, carbs:40, fat:9, fiber:4, diet:"vegetarian", allergens:["dairy","gluten"], tags:["no-cook"],
  ingredients:[[1,"cup","plain nonfat Greek yogurt","Dairy & eggs"],[0.5,"cup","blueberries (fresh or frozen)","Produce"],[0.25,"cup","granola","Pantry"],[1,"tsp","honey","Pantry"]],
  steps:["Spoon the yogurt into a bowl.","Top with berries, granola and a drizzle of honey."],
  tip:"Frozen berries are cheaper and thaw into a nice syrup by the time you eat." },

{ id:"b-burritos", name:"Make-ahead breakfast burritos", meal:"breakfast", minutes:20, servings:4,
  kcal:420, protein:26, carbs:43, fat:16, fiber:7, diet:"vegetarian", allergens:["egg","dairy","gluten"], tags:["make-ahead","freezer"],
  ingredients:[[6,"","eggs","Dairy & eggs"],[0.5,"cup","liquid egg whites","Dairy & eggs"],[1,"can","black beans (15 oz)","Canned & jars","drained"],[0.5,"cup","salsa","Canned & jars"],[0.5,"cup","shredded cheddar","Dairy & eggs"],[4,"","flour tortillas (8-inch)","Bakery"]],
  steps:["Scramble the eggs and egg whites in a nonstick pan until just set.","Warm the beans in the microwave for 1 minute.","Fill each tortilla with eggs, beans, salsa and cheese, then roll tightly.","Eat one now. Wrap the rest in foil and refrigerate (4 days) or freeze (2 months).","To reheat from frozen: unwrap, cover with a damp paper towel, microwave 2 minutes, flipping halfway."],
  tip:"Let the fillings cool before rolling so the tortillas don't get soggy." },

{ id:"b-cottage-toast", name:"Cottage cheese and tomato toast", meal:"breakfast", minutes:5, servings:1,
  kcal:320, protein:27, carbs:40, fat:6, fiber:6, diet:"vegetarian", allergens:["dairy","gluten"], tags:["no-cook"],
  ingredients:[[2,"slice","whole wheat bread","Bakery"],[0.75,"cup","2% cottage cheese","Dairy & eggs"],[1,"","tomato","Produce","sliced"],[0.5,"tsp","everything bagel seasoning","Pantry"]],
  steps:["Toast the bread.","Spread the cottage cheese on top and add tomato slices.","Finish with everything bagel seasoning and black pepper."],
  tip:"Swap tomato for sliced peaches and cinnamon on days you want it sweet." },

{ id:"b-tofu-tacos", name:"Tofu scramble breakfast tacos", meal:"breakfast", minutes:12, servings:1,
  kcal:445, protein:37, carbs:48, fat:15, fiber:10, diet:"vegan", allergens:["soy"], tags:[],
  ingredients:[[5,"oz","firm tofu","Produce"],[0.5,"cup","black beans","Canned & jars","rinsed"],[2,"","corn tortillas","Bakery"],[2,"tbsp","salsa","Canned & jars"],[0.25,"tsp","turmeric","Pantry"],[0.5,"tsp","cumin","Pantry"]],
  steps:["Pat the tofu dry and crumble it into a hot nonstick pan.","Add turmeric, cumin, salt and pepper. Cook 5 minutes, stirring.","Stir in the beans until warm.","Warm the tortillas in a dry pan, fill, and top with salsa."],
  tip:"Turmeric makes the tofu look like scrambled egg; a pinch of black salt makes it taste like it." },

{ id:"b-smoothie", name:"Peanut butter protein smoothie", meal:"breakfast", minutes:3, servings:1,
  kcal:350, protein:30, carbs:34, fat:12, fiber:4, diet:"vegetarian", allergens:["dairy","peanut","tree nut"], tags:["no-cook"],
  ingredients:[[1,"","banana","Produce","frozen works best"],[1,"cup","unsweetened almond milk","Dairy & eggs"],[1,"scoop","vanilla or chocolate whey protein","Pantry"],[1,"tbsp","peanut butter","Pantry"],[1,"cup","ice","Frozen"]],
  steps:["Add everything to a blender.","Blend until smooth, about 45 seconds."],
  tip:"Peel and freeze ripe bananas in halves. They make the smoothie thick like a milkshake." },

{ id:"b-baked-oats", name:"Apple cinnamon baked oatmeal", meal:"breakfast", minutes:10, servings:4,
  kcal:340, protein:17, carbs:53, fat:8, fiber:6, diet:"vegetarian", allergens:["egg","dairy"], tags:["make-ahead"],
  ingredients:[[2,"cup","rolled oats","Grains & pasta"],[2,"","eggs","Dairy & eggs"],[1.5,"cup","milk (2% or any)","Dairy & eggs"],[1,"cup","plain nonfat Greek yogurt","Dairy & eggs"],[2,"","apples","Produce","diced"],[2,"tbsp","maple syrup","Pantry"],[1,"tsp","baking powder","Pantry"],[2,"tsp","cinnamon","Pantry"]],
  steps:["Heat the oven to 375°F (190°C) and grease an 8×8 baking dish.","Whisk the eggs, milk, yogurt, maple syrup, baking powder and cinnamon in a bowl.","Stir in the oats and apples, then pour into the dish.","Bake 35 minutes until set in the middle.","Cut into 4 squares. Keeps 5 days in the fridge."],
  tip:"Reheat a square for 45 seconds and add a spoon of yogurt on top." },

{ id:"b-choc-oats", name:"Chocolate peanut butter oats", meal:"breakfast", minutes:5, servings:1,
  kcal:390, protein:18, carbs:51, fat:16, fiber:8, diet:"vegan", allergens:["soy","peanut"], tags:["make-ahead","no-cook"],
  ingredients:[[0.5,"cup","rolled oats","Grains & pasta"],[1,"cup","unsweetened soy milk","Dairy & eggs"],[1,"tbsp","cocoa powder","Pantry"],[1,"tbsp","peanut butter","Pantry"],[0.5,"","banana","Produce"]],
  steps:["Stir the oats, soy milk and cocoa together in a jar.","Refrigerate overnight, or microwave 2 minutes for hot oats.","Top with peanut butter and sliced banana."],
  tip:"Soy milk has about 7 g protein a cup, far more than almond or oat milk." },

/* ---------------- Lunch ---------------- */
{ id:"l-caesar-wrap", name:"Chicken Caesar wrap", meal:"lunch", minutes:8, servings:1,
  kcal:380, protein:33, carbs:30, fat:13, fiber:3, diet:"any", allergens:["gluten","dairy","fish"], tags:["no-cook","packable"],
  ingredients:[[3,"oz","cooked chicken breast (rotisserie works)","Meat & seafood"],[1,"","large flour tortilla","Bakery"],[1.5,"cup","chopped romaine","Produce"],[2,"tbsp","light Caesar dressing","Canned & jars"],[1,"tbsp","grated parmesan","Dairy & eggs"]],
  steps:["Toss the romaine with dressing and parmesan.","Lay the chicken and salad down the middle of the tortilla.","Fold in the sides and roll tightly. Cut in half."],
  tip:"A store rotisserie chicken gives you about 4 lunches of meat for one price." },

{ id:"l-turkey-pita", name:"Turkey hummus pita", meal:"lunch", minutes:5, servings:1,
  kcal:345, protein:24, carbs:45, fat:8, fiber:7, diet:"any", allergens:["gluten","sesame"], tags:["no-cook","packable","deli"],
  ingredients:[[1,"","whole wheat pita","Bakery"],[3,"oz","sliced turkey breast","Meat & seafood"],[2,"tbsp","hummus","Dairy & eggs"],[0.5,"","cucumber","Produce","sliced"],[1,"","tomato","Produce","sliced"],[1,"cup","baby spinach","Produce"]],
  steps:["Cut the pita in half and open the pockets.","Spread hummus inside each half.","Fill with turkey, spinach, cucumber and tomato."],
  tip:"Pack the tomato separately if you're eating it hours later so the bread stays firm." },

{ id:"l-tuna-plate", name:"Tuna salad snack plate", meal:"lunch", minutes:7, servings:1,
  kcal:410, protein:35, carbs:47, fat:10, fiber:7, diet:"pescatarian", allergens:["fish","egg","dairy","gluten"], tags:["no-cook","packable"],
  ingredients:[[1,"can","tuna in water (5 oz)","Canned & jars","drained"],[1,"tbsp","light mayo","Canned & jars"],[2,"tbsp","plain nonfat Greek yogurt","Dairy & eggs"],[1,"","celery stalk","Produce","diced"],[6,"","whole grain crackers","Pantry"],[1,"","apple","Produce"]],
  steps:["Mix the tuna, mayo, yogurt and celery with a squeeze of mustard, salt and pepper.","Serve with crackers and a sliced apple."],
  tip:"Canned light tuna is lower in mercury than albacore." },

{ id:"l-chickpea-salad", name:"Chickpea Greek salad", meal:"lunch", minutes:10, servings:1,
  kcal:395, protein:16, carbs:42, fat:19, fiber:11, diet:"vegetarian", allergens:["dairy"], tags:["no-cook","packable"],
  ingredients:[[0.75,"cup","chickpeas","Canned & jars","rinsed"],[0.5,"","cucumber","Produce","diced"],[1,"cup","cherry tomatoes","Produce","halved"],[0.25,"","red onion","Produce","thinly sliced"],[1,"oz","feta","Dairy & eggs"],[2,"tsp","olive oil","Pantry"],[0.5,"","lemon","Produce"]],
  steps:["Combine the chickpeas, cucumber, tomatoes and onion in a bowl or container.","Dress with olive oil, lemon juice, salt, pepper and a pinch of oregano.","Crumble feta on top."],
  tip:"It tastes better after an hour in the fridge, so it's ideal to make the night before." },

{ id:"l-quinoa-bowl", name:"Black bean and corn quinoa bowl", meal:"lunch", minutes:10, servings:1,
  kcal:410, protein:17, carbs:65, fat:11, fiber:15, diet:"vegan", allergens:[], tags:["packable"],
  ingredients:[[0.75,"cup","cooked quinoa","Grains & pasta"],[0.5,"cup","black beans","Canned & jars","rinsed"],[0.25,"cup","corn (frozen or canned)","Frozen"],[0.25,"","avocado","Produce","diced"],[0.25,"cup","salsa","Canned & jars"],[0.5,"","lime","Produce"]],
  steps:["Add the quinoa, beans and corn to a bowl.","Top with avocado and salsa.","Squeeze lime over everything and season with salt."],
  tip:"Microwavable quinoa pouches make this a 3-minute lunch." },

{ id:"l-egg-salad", name:"Greek yogurt egg salad sandwich", meal:"lunch", minutes:10, servings:1,
  kcal:325, protein:24, carbs:30, fat:12, fiber:4, diet:"vegetarian", allergens:["egg","dairy","gluten"], tags:["packable"],
  ingredients:[[2,"","hard-boiled eggs","Dairy & eggs"],[2,"tbsp","plain nonfat Greek yogurt","Dairy & eggs"],[1,"tsp","mustard","Canned & jars"],[2,"slice","whole wheat bread","Bakery"],[2,"leaf","lettuce","Produce"]],
  steps:["Chop the eggs and mix with yogurt, mustard, salt and pepper.","Spread on bread with lettuce."],
  tip:"Boil 6 eggs on Sunday (10 minutes, then ice water). They keep peeled-or-not for a week." },

/* ---------------- Dinner ---------------- */
{ id:"d-fajitas", name:"Sheet-pan chicken fajitas", meal:"dinner", minutes:15, servings:3,
  kcal:495, protein:42, carbs:44, fat:15, fiber:4, diet:"any", allergens:["gluten","dairy"], tags:["sheet-pan"],
  ingredients:[[1,"lb","boneless chicken breast","Meat & seafood","sliced into strips"],[2,"","bell peppers","Produce","sliced"],[1,"","onion","Produce","sliced"],[1,"tbsp","olive oil","Pantry"],[2,"tbsp","fajita or taco seasoning","Pantry"],[6,"","small flour tortillas (6-inch)","Bakery"],[0.5,"cup","salsa","Canned & jars"],[6,"tbsp","light sour cream","Dairy & eggs"]],
  steps:["Heat the oven to 425°F (220°C).","Toss the chicken, peppers and onion with oil and seasoning on a sheet pan.","Spread out in one layer and roast 20 minutes, until the chicken is cooked through.","Warm the tortillas and fill with the chicken and veggies, salsa and sour cream."],
  tip:"Leftovers make a great lunch bowl over rice or lettuce." },

{ id:"d-taco-bowls", name:"Turkey taco rice bowls", meal:"dinner", minutes:20, servings:4,
  kcal:470, protein:34, carbs:50, fat:15, fiber:8, diet:"any", allergens:["dairy"], tags:["one-pan"],
  ingredients:[[1,"lb","93% lean ground turkey","Meat & seafood"],[2,"tbsp","taco seasoning","Pantry"],[2,"cup","cooked rice","Grains & pasta"],[1,"can","black beans (15 oz)","Canned & jars","rinsed"],[1,"cup","corn (frozen or canned)","Frozen"],[1,"cup","salsa","Canned & jars"],[0.5,"cup","shredded cheddar","Dairy & eggs"],[2,"cup","shredded lettuce","Produce"]],
  steps:["Brown the turkey in a large pan over medium-high, breaking it up, about 7 minutes.","Add taco seasoning and ⅓ cup water. Simmer 2 minutes.","Stir in the beans and corn until hot.","Serve over rice with lettuce, salsa and cheese."],
  tip:"Pack leftovers with the lettuce and salsa in a separate container." },

{ id:"d-tomato-pasta", name:"One-pot creamy tomato pasta with chicken sausage", meal:"dinner", minutes:25, servings:4,
  kcal:450, protein:28, carbs:60, fat:12, fiber:5, diet:"any", allergens:["gluten","dairy"], tags:["one-pan"],
  ingredients:[[8,"oz","short pasta (penne or rotini)","Grains & pasta"],[12,"oz","precooked chicken sausage","Meat & seafood","sliced"],[1,"can","crushed tomatoes (28 oz)","Canned & jars"],[3,"cup","low-sodium chicken broth","Canned & jars"],[3,"cup","baby spinach","Produce"],[0.33,"cup","grated parmesan","Dairy & eggs"],[3,"clove","garlic","Produce","minced"],[1,"tsp","Italian seasoning","Pantry"]],
  steps:["Brown the sausage slices in a large pot for 4 minutes. Add garlic for 30 seconds.","Add the tomatoes, broth, pasta and Italian seasoning. Bring to a boil.","Lower to a simmer and cook 12–14 minutes, stirring often, until the pasta is tender.","Stir in the spinach and parmesan until the spinach wilts."],
  tip:"Add a splash of water when reheating. The pasta soaks up sauce overnight." },

{ id:"d-salmon", name:"Honey garlic salmon with rice and broccoli", meal:"dinner", minutes:20, servings:2,
  kcal:515, protein:35, carbs:49, fat:19, fiber:4, diet:"pescatarian", allergens:["fish","soy","gluten"], tags:["sheet-pan"],
  ingredients:[[2,"","salmon fillets (5 oz each)","Meat & seafood"],[1,"tbsp","honey","Pantry"],[1,"tbsp","low-sodium soy sauce","Pantry"],[2,"clove","garlic","Produce","minced"],[1.5,"cup","cooked rice","Grains & pasta"],[2,"cup","broccoli florets","Produce"]],
  steps:["Heat the oven to 400°F (200°C).","Mix the honey, soy sauce and garlic. Brush over the salmon on a lined sheet pan.","Add the broccoli to the pan with a little salt and pepper.","Bake 12–14 minutes until the salmon flakes easily.","Serve with rice."],
  tip:"Frozen salmon fillets are cheaper. Thaw overnight in the fridge." },

{ id:"d-stir-fry", name:"Chicken stir-fry with frozen veggies", meal:"dinner", minutes:20, servings:3,
  kcal:445, protein:40, carbs:48, fat:9, fiber:4, diet:"any", allergens:["soy","gluten"], tags:["one-pan"],
  ingredients:[[1,"lb","boneless chicken breast","Meat & seafood","bite-size pieces"],[12,"oz","bag frozen stir-fry vegetables","Frozen"],[3,"tbsp","teriyaki or stir-fry sauce","Canned & jars"],[1,"tbsp","neutral oil","Pantry"],[2.25,"cup","cooked rice","Grains & pasta"]],
  steps:["Heat oil in a large pan over high heat.","Cook the chicken 5–6 minutes until browned and cooked through. Move it to a plate.","Cook the frozen vegetables 5 minutes until hot.","Return the chicken, add the sauce and toss 1 minute.","Serve over rice."],
  tip:"Don't crowd the pan. Cook the chicken in two batches if it doesn't fit in one layer." },

{ id:"d-chili", name:"Slow-cooker chicken chili", meal:"dinner", minutes:15, servings:6,
  kcal:375, protein:39, carbs:31, fat:10, fiber:8, diet:"any", allergens:["dairy"], tags:["slow-cooker","freezer","batch"],
  ingredients:[[1.5,"lb","boneless chicken breast","Meat & seafood"],[2,"can","white or kidney beans (15 oz)","Canned & jars","rinsed"],[1,"can","diced tomatoes (14.5 oz)","Canned & jars"],[1,"","onion","Produce","diced"],[1,"cup","corn (frozen)","Frozen"],[2,"cup","low-sodium chicken broth","Canned & jars"],[2,"tbsp","chili powder","Pantry"],[1,"tsp","cumin","Pantry"],[6,"tbsp","light sour cream","Dairy & eggs"],[0.75,"cup","shredded cheddar","Dairy & eggs"]],
  steps:["Put everything except the sour cream and cheese in a slow cooker.","Cook on low 6 hours or high 3 hours.","Shred the chicken with two forks right in the pot.","Serve topped with sour cream and cheese."],
  tip:"Freeze single portions in containers for nights you don't want to cook." },

{ id:"d-meatballs", name:"Turkey meatballs with marinara spaghetti", meal:"dinner", minutes:15, servings:4,
  kcal:465, protein:33, carbs:48, fat:16, fiber:5, diet:"any", allergens:["egg","dairy","gluten"], tags:["sheet-pan","freezer"],
  ingredients:[[1,"lb","93% lean ground turkey","Meat & seafood"],[1,"","egg","Dairy & eggs"],[0.33,"cup","breadcrumbs","Pantry"],[0.25,"cup","grated parmesan","Dairy & eggs"],[1,"tsp","Italian seasoning","Pantry"],[2,"cup","marinara sauce","Canned & jars"],[6,"oz","spaghetti","Grains & pasta"]],
  steps:["Heat the oven to 400°F (200°C).","Mix the turkey, egg, breadcrumbs, parmesan, Italian seasoning and a pinch of salt. Roll into 16 balls.","Bake on a lined sheet pan for 18 minutes.","Meanwhile cook the spaghetti and warm the marinara.","Toss the meatballs in the sauce and serve over pasta."],
  tip:"Wet your hands when rolling and the mixture won't stick." },

{ id:"d-lemon-chicken", name:"Lemon herb chicken and potatoes", meal:"dinner", minutes:15, servings:3,
  kcal:435, protein:40, carbs:44, fat:11, fiber:6, diet:"any", allergens:[], tags:["sheet-pan"],
  ingredients:[[1,"lb","boneless chicken breast","Meat & seafood","cut in chunks"],[1.5,"lb","baby potatoes","Produce","halved"],[2,"cup","green beans","Produce","trimmed"],[1.5,"tbsp","olive oil","Pantry"],[1,"","lemon","Produce"],[3,"clove","garlic","Produce","minced"],[1,"tsp","dried oregano","Pantry"]],
  steps:["Heat the oven to 425°F (220°C).","Toss the potatoes with half the oil, salt and pepper. Roast 15 minutes.","Toss the chicken and green beans with the rest of the oil, garlic, oregano and lemon zest.","Add to the pan and roast 18–20 more minutes.","Squeeze the lemon over everything before serving."],
  tip:"Cut the potatoes small (about 1 inch) so they finish at the same time as the chicken." },

{ id:"d-sweet-potato-tacos", name:"Black bean and sweet potato tacos", meal:"dinner", minutes:15, servings:3,
  kcal:475, protein:14, carbs:77, fat:15, fiber:17, diet:"vegan", allergens:[], tags:["sheet-pan"],
  ingredients:[[2,"","sweet potatoes","Produce","½-inch cubes"],[1,"can","black beans (15 oz)","Canned & jars","rinsed"],[1,"tbsp","olive oil","Pantry"],[1,"tsp","cumin","Pantry"],[1,"tsp","chili powder","Pantry"],[9,"","corn tortillas","Bakery"],[0.5,"cup","salsa","Canned & jars"],[1,"","avocado","Produce"],[1,"","lime","Produce"]],
  steps:["Heat the oven to 425°F (220°C).","Toss the sweet potato with oil, cumin, chili powder and salt. Roast 25 minutes.","Warm the beans with a pinch of cumin.","Fill warm tortillas with sweet potato, beans, avocado and salsa. Squeeze lime on top."],
  tip:"Add a fried egg or crumbled cotija for more protein if you eat eggs or dairy." },

{ id:"d-chickpea-curry", name:"Coconut chickpea curry", meal:"dinner", minutes:20, servings:4,
  kcal:400, protein:13, carbs:59, fat:13, fiber:10, diet:"vegan", allergens:[], tags:["one-pan","freezer"],
  ingredients:[[2,"can","chickpeas (15 oz)","Canned & jars","rinsed"],[1,"can","light coconut milk (13.5 oz)","Canned & jars"],[1,"can","diced tomatoes (14.5 oz)","Canned & jars"],[1,"","onion","Produce","diced"],[3,"cup","baby spinach","Produce"],[2,"tbsp","curry powder","Pantry"],[1,"tbsp","neutral oil","Pantry"],[2,"cup","cooked brown rice","Grains & pasta"]],
  steps:["Cook the onion in oil over medium for 5 minutes.","Add the curry powder and stir 30 seconds.","Add the chickpeas, coconut milk and tomatoes. Simmer 12 minutes.","Stir in the spinach until wilted. Season with salt.","Serve over rice."],
  tip:"Stir in a spoon of Greek yogurt or add cubed tofu for more protein." },

{ id:"d-shrimp-noodles", name:"Garlic butter shrimp noodles", meal:"dinner", minutes:20, servings:2,
  kcal:450, protein:46, carbs:48, fat:9, fiber:5, diet:"pescatarian", allergens:["shellfish","gluten","dairy"], tags:["one-pan"],
  ingredients:[[12,"oz","peeled raw shrimp (frozen is fine)","Frozen"],[4,"oz","spaghetti","Grains & pasta"],[2,"cup","broccoli or snap peas","Produce"],[1,"tbsp","butter","Dairy & eggs"],[3,"clove","garlic","Produce","minced"],[2,"tbsp","grated parmesan","Dairy & eggs"],[0.5,"","lemon","Produce"]],
  steps:["Cook the spaghetti, adding the broccoli for the last 3 minutes. Drain, saving ¼ cup of pasta water.","Melt the butter in the pot, add the garlic for 30 seconds, then the shrimp.","Cook the shrimp 2 minutes per side until pink.","Toss in the pasta, broccoli, parmesan, lemon juice and a splash of pasta water."],
  tip:"Shrimp cooks fast. Pull it when it curls into a C, not an O." },

{ id:"d-beef-broccoli", name:"Beef and broccoli", meal:"dinner", minutes:25, servings:3,
  kcal:515, protein:41, carbs:50, fat:16, fiber:4, diet:"any", allergens:["soy","gluten"], tags:["one-pan"],
  ingredients:[[1,"lb","sirloin or flank steak","Meat & seafood","thin slices"],[4,"cup","broccoli florets","Produce"],[3,"tbsp","low-sodium soy sauce","Pantry"],[1,"tbsp","brown sugar","Pantry"],[1,"tbsp","cornstarch","Pantry"],[1,"tbsp","neutral oil","Pantry"],[2,"clove","garlic","Produce","minced"],[2.25,"cup","cooked rice","Grains & pasta"]],
  steps:["Whisk the soy sauce, brown sugar, cornstarch, garlic and ½ cup water.","Steam or microwave the broccoli 3 minutes.","Sear the beef in hot oil over high heat, 2 minutes per side, in batches.","Add the sauce and broccoli and stir until glossy, about 1 minute.","Serve over rice."],
  tip:"Slice the beef across the grain while slightly frozen for thin, tender strips." },

{ id:"d-greek-bowls", name:"Greek chicken pita bowls", meal:"dinner", minutes:20, servings:3,
  kcal:445, protein:46, carbs:41, fat:11, fiber:6, diet:"any", allergens:["gluten","dairy"], tags:["sheet-pan"],
  ingredients:[[1,"lb","boneless chicken breast","Meat & seafood"],[2,"tsp","olive oil","Pantry"],[2,"tsp","dried oregano","Pantry"],[1,"","lemon","Produce"],[3,"","whole wheat pitas","Bakery"],[1,"","cucumber","Produce"],[1,"cup","cherry tomatoes","Produce"],[0.75,"cup","plain nonfat Greek yogurt","Dairy & eggs"],[1,"clove","garlic","Produce","minced"]],
  steps:["Rub the chicken with oil, oregano, lemon zest, salt and pepper.","Cook in a pan or under the broiler 6–7 minutes per side, then slice.","Make quick tzatziki: grate half the cucumber into the yogurt with garlic, lemon juice and salt.","Chop the rest of the cucumber and the tomatoes.","Serve the chicken with veggies, tzatziki and warm pita."],
  tip:"Squeeze the grated cucumber in a towel so the tzatziki stays thick." },

{ id:"d-lentil-bolognese", name:"Lentil bolognese", meal:"dinner", minutes:15, servings:4,
  kcal:510, protein:22, carbs:88, fat:8, fiber:12, diet:"vegan", allergens:["gluten"], tags:["one-pan","freezer"],
  ingredients:[[1,"cup","dry red lentils","Grains & pasta"],[1,"jar","marinara sauce (24 oz)","Canned & jars"],[1,"","onion","Produce","diced"],[1,"","carrot","Produce","grated"],[1,"tbsp","olive oil","Pantry"],[8,"oz","spaghetti or penne","Grains & pasta"]],
  steps:["Cook the onion and carrot in oil for 5 minutes.","Add the lentils, marinara and 2 cups water. Simmer 20 minutes, stirring now and then, until the lentils are soft.","Cook the pasta while the sauce simmers.","Toss the pasta with the sauce."],
  tip:"Red lentils melt into the sauce, so picky eaters rarely notice them." },

{ id:"d-cod", name:"Lemon baked cod with potatoes and green beans", meal:"dinner", minutes:15, servings:2,
  kcal:455, protein:37, carbs:47, fat:14, fiber:9, diet:"pescatarian", allergens:["fish","dairy"], tags:["sheet-pan"],
  ingredients:[[12,"oz","cod fillets","Meat & seafood"],[1,"lb","baby potatoes","Produce","halved"],[2,"cup","green beans","Produce"],[1,"tbsp","olive oil","Pantry"],[1,"tbsp","butter","Dairy & eggs","melted"],[1,"","lemon","Produce"],[1,"tsp","paprika","Pantry"]],
  steps:["Heat the oven to 425°F (220°C). Roast the potatoes with oil and salt for 15 minutes.","Add the green beans and cod to the pan.","Brush the cod with melted butter, lemon juice and paprika.","Roast 12 more minutes until the fish flakes."],
  tip:"Any white fish works: cod, tilapia, haddock or pollock." },

{ id:"d-tofu-noodles", name:"Peanut tofu noodle stir-fry", meal:"dinner", minutes:25, servings:3,
  kcal:515, protein:32, carbs:63, fat:17, fiber:5, diet:"vegan", allergens:["soy","peanut"], tags:["one-pan"],
  ingredients:[[14,"oz","extra-firm tofu","Produce","cubed"],[6,"oz","rice noodles or spaghetti","Grains & pasta"],[12,"oz","bag frozen stir-fry vegetables","Frozen"],[2,"tbsp","peanut butter","Pantry"],[2,"tbsp","low-sodium soy sauce","Pantry"],[1,"tbsp","maple syrup","Pantry"],[1,"","lime","Produce"],[1,"tsp","sriracha (optional)","Canned & jars"]],
  steps:["Press the tofu dry with towels and cube it.","Brown the tofu in a nonstick pan over medium-high, 8 minutes, turning.","Cook the noodles. Whisk the peanut butter, soy sauce, maple syrup, lime juice, sriracha and 3 tbsp hot water.","Cook the vegetables in the pan 5 minutes, then add the noodles, tofu and sauce and toss."],
  tip:"Tossing the tofu in 1 tbsp cornstarch before browning makes it crispy." },

/* ---------------- Snacks ---------------- */
{ id:"s-apple-pb", name:"Apple with peanut butter", meal:"snack", minutes:2, servings:1,
  kcal:190, protein:5, carbs:28, fat:8, fiber:5, diet:"vegan", allergens:["peanut"], tags:["no-cook"],
  ingredients:[[1,"","apple","Produce"],[1,"tbsp","peanut butter","Pantry"]],
  steps:["Slice the apple and dip in peanut butter."], tip:"Measure the peanut butter with a real spoon. It's easy to double it by eye." },
{ id:"s-yogurt-honey", name:"Greek yogurt with honey and cinnamon", meal:"snack", minutes:2, servings:1,
  kcal:120, protein:17, carbs:12, fat:1, fiber:0, diet:"vegetarian", allergens:["dairy"], tags:["no-cook"],
  ingredients:[[0.75,"cup","plain nonfat Greek yogurt","Dairy & eggs"],[1,"tsp","honey","Pantry"],[0.25,"tsp","cinnamon","Pantry"]],
  steps:["Top the yogurt with honey and cinnamon."], tip:"" },
{ id:"s-cheese-grapes", name:"String cheese and grapes", meal:"snack", minutes:1, servings:1,
  kcal:185, protein:8, carbs:28, fat:6, fiber:1.5, diet:"vegetarian", allergens:["dairy"], tags:["no-cook","packable"],
  ingredients:[[1,"","part-skim string cheese","Dairy & eggs"],[1,"cup","grapes","Produce"]],
  steps:["Pack together. That's it."], tip:"Frozen grapes taste like little sorbet bites." },
{ id:"s-hummus-veg", name:"Hummus and veggie sticks", meal:"snack", minutes:5, servings:1,
  kcal:180, protein:6, carbs:17, fat:10, fiber:4, diet:"vegan", allergens:["sesame"], tags:["no-cook","packable"],
  ingredients:[[0.25,"cup","hummus","Dairy & eggs"],[1,"","carrot","Produce","sticks"],[0.5,"","cucumber","Produce","sticks"],[0.5,"","bell pepper","Produce","strips"]],
  steps:["Cut the veggies into sticks and dip."], tip:"Cut a few days of veggies at once and keep them in water in the fridge." },
{ id:"s-cottage-pineapple", name:"Cottage cheese and pineapple", meal:"snack", minutes:2, servings:1,
  kcal:135, protein:12, carbs:16, fat:3, fiber:1, diet:"vegetarian", allergens:["dairy"], tags:["no-cook"],
  ingredients:[[0.5,"cup","2% cottage cheese","Dairy & eggs"],[0.5,"cup","pineapple chunks","Produce"]],
  steps:["Top the cottage cheese with pineapple."], tip:"" },
{ id:"s-shake", name:"Protein shake", meal:"snack", minutes:1, servings:1,
  kcal:120, protein:24, carbs:3, fat:1.5, fiber:0, diet:"vegetarian", allergens:["dairy"], tags:["no-cook"],
  ingredients:[[1,"scoop","whey protein","Pantry"]],
  steps:["Shake with 10 oz cold water or blend with ice."], tip:"The easiest way to close a protein gap at the end of the day." },
{ id:"s-eggs-tomatoes", name:"Hard-boiled eggs and cherry tomatoes", meal:"snack", minutes:2, servings:1,
  kcal:170, protein:14, carbs:7, fat:10, fiber:2, diet:"vegetarian", allergens:["egg"], tags:["no-cook","packable"],
  ingredients:[[2,"","hard-boiled eggs","Dairy & eggs"],[1,"cup","cherry tomatoes","Produce"]],
  steps:["Peel the eggs, season with salt, pepper or everything bagel seasoning."], tip:"" },
{ id:"s-popcorn", name:"Popcorn and almonds", meal:"snack", minutes:3, servings:1,
  kcal:165, protein:6, carbs:22, fat:7, fiber:5, diet:"vegan", allergens:["tree nut"], tags:["packable"],
  ingredients:[[3,"cup","air-popped or light popcorn","Pantry"],[10,"","almonds","Pantry"]],
  steps:["Toss together. Add a pinch of salt or cinnamon."], tip:"3 cups of popcorn is a big bowl for under 100 calories." },
{ id:"s-edamame", name:"Edamame with sea salt", meal:"snack", minutes:4, servings:1,
  kcal:190, protein:18, carbs:14, fat:8, fiber:8, diet:"vegan", allergens:["soy"], tags:[],
  ingredients:[[1,"cup","shelled edamame (frozen)","Frozen"]],
  steps:["Microwave 3 minutes with a splash of water, then sprinkle with salt."], tip:"" },
{ id:"s-chocolate", name:"Dark chocolate and strawberries", meal:"snack", minutes:2, servings:1,
  kcal:170, protein:3, carbs:21, fat:9, fiber:4, diet:"vegan", allergens:[], tags:["no-cook","treat"],
  ingredients:[[20,"g","dark chocolate (70%)","Pantry"],[1,"cup","strawberries","Produce"]],
  steps:["Eat slowly. You earned it."], tip:"Two squares of good dark chocolate satisfy a craving better than a whole bar of cheap chocolate." }
];
